import type { Metadata } from 'next'
import '@/styles/globals.scss'
import { Montserrat } from 'next/font/google'
import ProvidersWrapper from '@/containers/providers-wrapper'

const montserrat = Montserrat({
	subsets: ["latin"],
	variable: "--font-montserrat",
})

export const metadata: Metadata = {
  title: "Appro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={montserrat.variable}>
			<body>
				<ProvidersWrapper>{children}</ProvidersWrapper>
			</body>
		</html>
  );
}
