import type { Metadata } from "next";
import "@/styles/globals.css";
import "@/styles/globals.scss";
import ProvidersWrapper from "@/containers/providers-wrapper";

export const metadata: Metadata = {
  title: "Appro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ProvidersWrapper>
          {children}
        </ProvidersWrapper>
      </body>
    </html>
  );
}
